"""test_export.py — Export pipeline and ASS format tests for VideoCaptionsAI"""
import os, sys, json, unittest

# Add project to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# ============================================================
# ASS Format Tests
# ============================================================
class TestASSFormat(unittest.TestCase):
    """Verify ASS file format correctness"""

    def test_header_contains_required_fields(self):
        header = """[Script Info]
; Script generated by VideoCaptionsAI
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes"""
        self.assertIn("PlayResX: 1920", header)
        self.assertIn("PlayResY: 1080", header)
        self.assertIn("ScriptType: v4.00+", header)

    def test_style_format_has_23_fields(self):
        fmt = "Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
        fields = [f.strip() for f in fmt.split(",")]
        self.assertEqual(len(fields), 23)
        required = ["Alignment", "MarginL", "MarginR", "MarginV", "Fontname", "Fontsize"]
        for field in required:
            self.assertIn(field, fields, f"Missing field: {field}")

    def test_event_format_has_10_fields(self):
        fmt = "Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        fields = [f.strip() for f in fmt.split(",")]
        self.assertEqual(len(fields), 10)
        self.assertIn("MarginL", fields)
        self.assertIn("MarginR", fields)
        self.assertIn("MarginV", fields)

    def test_style_line_format(self):
        """Generate a style line and verify all fields"""
        style = {
            "Name": "Default", "FontName": "Arial", "FontSize": 64,
            "PrimaryColour": "&H00FFFFFF", "SecondaryColour": "&H00000000",
            "OutlineColour": "&H00000000", "BackColour": "&H00000000",
            "Bold": 0, "Italic": 0, "Underline": 0, "StrikeOut": 0,
            "ScaleX": 100, "ScaleY": 100, "Spacing": 0, "Angle": 0,
            "BorderStyle": 1, "Outline": 2, "Shadow": 0,
            "Alignment": 2, "MarginL": 10, "MarginR": 10, "MarginV": 10, "Encoding": 1
        }
        line = f"Style: {style['Name']},{style['FontName']},{style['FontSize']},{style['PrimaryColour']},{style['SecondaryColour']},{style['OutlineColour']},{style['BackColour']},{style['Bold']},{style['Italic']},{style['Underline']},{style['StrikeOut']},{style['ScaleX']},{style['ScaleY']},{style['Spacing']},{style['Angle']},{style['BorderStyle']},{style['Outline']},{style['Shadow']},{style['Alignment']},{style['MarginL']},{style['MarginR']},{style['MarginV']},{style['Encoding']}"
        self.assertEqual(len(line.split(",")), 23)

    def test_dialogue_event_uses_zero_margins_for_style_defaults(self):
        """In ASS, event margins of 0 mean use style defaults"""
        event = "Dialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,Hello World"
        parts = event.split(",")
        # Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        self.assertEqual(parts[5], "0", "MarginL should be 0 (style default)")
        self.assertEqual(parts[6], "0", "MarginR should be 0 (style default)")
        self.assertEqual(parts[7], "0", "MarginV should be 0 (style default)")


# ============================================================
# Coordinate Consistency Tests
# ============================================================
class TestCoordinateConsistency(unittest.TestCase):
    """Verify preview CoordinateMapper matches ASS specification"""

    def test_alignment_numpad_mapping(self):
        """Verify standard numpad alignment mapping"""
        def h_align(a):
            m = a % 3
            return "left" if m == 1 else ("right" if m == 0 else "center")
        def v_align(a):
            if a <= 3: return "bottom"
            if a >= 7: return "top"
            return "middle"

        expected = {
            1: ("left", "bottom"), 2: ("center", "bottom"), 3: ("right", "bottom"),
            4: ("left", "middle"), 5: ("center", "middle"), 6: ("right", "middle"),
            7: ("left", "top"), 8: ("center", "top"), 9: ("right", "top"),
        }
        for a, (eh, ev) in expected.items():
            self.assertEqual(h_align(a), eh, f"Align {a}: h")
            self.assertEqual(v_align(a), ev, f"Align {a}: v")

    def test_ass_margin_range(self):
        """ASS margins valid range: 0-999"""
        for m in [0, 10, 100, 999]:
            self.assertTrue(0 <= m <= 999)

    def test_font_size_range(self):
        """Font sizes typical range: 12-500"""
        for s in [12, 24, 48, 64, 128, 500]:
            self.assertTrue(12 <= s <= 500)

    def test_center_x_formula(self):
        """ASS spec: centerX = playResX/2 + marginL - marginR"""
        playResX = 1920
        marginL = 20
        marginR = 5
        expected_center_x = playResX / 2 + marginL - marginR
        self.assertEqual(expected_center_x, 1920/2 + 20 - 5)

    def test_time_format_conversion(self):
        """Verify ASS time format: H:MM:SS.cc"""
        def format_ass_time(seconds):
            h = int(seconds // 3600)
            m = int((seconds % 3600) // 60)
            s = f"{seconds % 60:.2f}"
            return f"{h}:{m:02d}:{s.zfill(5)}"

        self.assertEqual(format_ass_time(0), "0:00:00.00")
        self.assertEqual(format_ass_time(61.5), "0:01:01.50")
        self.assertEqual(format_ass_time(3661.75), "1:01:01.75")

    def test_scale_factor_formula(self):
        """Preview scale factor: s = contentRect.height / playResY"""
        # 1920x1080 video in 720x400 container with letterbox:
        # contentRect.height ≈ 400 (fits height), s = 400/1080 ≈ 0.370
        s = 400 / 1080
        # Verify: ASS fontSize=48 → CSS fontSize=48*s ≈ 17.78
        self.assertAlmostEqual(48 * s, 17.78, delta=0.1)


# ============================================================
# Style Rendering Tests
# ============================================================
class TestStyleRendering(unittest.TestCase):
    """Verify style properties map correctly between ASS and CSS"""

    def test_bold_to_css(self):
        self.assertEqual("bold" if True else "normal", "bold")
        self.assertEqual("bold" if False else "normal", "normal")

    def test_italic_to_css(self):
        self.assertEqual("italic" if True else "normal", "italic")

    def test_outline_to_textshadow(self):
        """ASS Outline maps to CSS text-shadow approximation"""
        outline = 2  # ASS outline width
        scale = 400 / 1080  # preview scale
        t = outline * scale
        self.assertGreater(t, 0)
        self.assertLess(t, 3)


if __name__ == "__main__":
    unittest.main(verbosity=2)
